### ISSUE TITLE
Run tests with pipelines imported by YAML files

### ISSUE THREAD

**Issue by Rob192** [etalab-ia/piaf-ml#39]
In production, the haystack API will be launched from a YAML file via Docker. Currently we test all configuration using manual instanciations of Retrievers, Readers and Pipeline. This is an opportunity for discrepancies between our test configurations and the configurations that are launched in production. Therefore the testing should be done with YAML files. 

A test configuration should now be used to generate a YAML file that will later be ingested by the evaluation script via the `pipeline.load_from_yaml` function.

**Comment by guillaumecherel** [comment]
@Rob192 @psorianom  @guillim I noticed a number of discrepancies between the `pipelines.yaml` files used for deployment and the pipelines built in the `retriever_reader_eval_squad.py` and `retriever_eval_squad.py` scripts. I didn't take care of the other scripts as I am not sure they are still in use. If some of them are, please let me know. 

Here is a list of the differences, can you tell me which version we should keep for each?

- Differences between `retriever_eval_squad.py` and `retriever_reader_eval_squad.py`
  - The ElasticsearchDocumentStore used is the same for all retriever types in the evaluation script (`retriever_reader_eval_squad.py`) except for "dpr", where it is given the argument `similarity = "dot_product"` instead of `"cosine"`. Is this correct or should we always use "cosine"?

- Differences between the evaluation script `retriever_reader_eval_squad.py` and the files `pipelines.yaml` used for deployment.
  - The parameter `embedding_dim` for the ElasticsearchDocumentStore is 768 in the evaluation script but 512 in `pipelines.yaml`.
  - The `search_fields` value is `["name", "text"]` in the evaluation script but `"text"` only in `pipelines.yaml`.
  - The `document_index` field is `"document_xp"` in the evaluation script but  `"document_elasticsearch"` in `pipelines.yaml`. Do we need to keep the different names in a deployment or evaluation settings? I imagine that could be needed if we sometimes run both settings with the same elasticsearch instance. If we don't we could use only one name.
  - `custom_mappings` are present in the evaluation script but not in `pipelines.yaml`
  - `context_window_size: 2000` present in `pipelines.yaml` but not in the evaluation script. Since it's used for presenting to the user a some text around the answer for context, I imagine we need it for deployment and therefore should keep it.

**Comment by guillim** [comment]
Good point. we definitely need to do some cleaning around here. I am very familiar with `pipeline.yaml` since I write them, but not really about the `.py`  files. Maybe a visio on that topic between @Rob192 @guillaumecherel and me would resolve this it faster ? What do you think ?

**Comment by psorianom** [comment]
>The ElasticsearchDocumentStore used is the same for all retriever types in the evaluation script (retriever_reader_eval_squad.py) except for "dpr", where it is given the argument similarity = "dot_product" instead of "cosine". Is this correct or should we always use "cosine"?

I think that it is recommended to use `dot_product` when using DPR

>The parameter embedding_dim for the ElasticsearchDocumentStore is 768 in the evaluation script but 512 in ...
This is part of the distilbert/distiluse issue. Tomorrow I will fix that for good. The `pipelines.yaml` file has 512 bc `distilbert` never made it to this file.
>context_window_size: 2000 present in pipelines.yaml but not in the evaluation script. Since it's used for presenting to the user a some text around the answer for context, I imagine we need it for deployment and therefore should keep it.
I am not sure about this parameter, I guess it is the haystack's preprocessing value. Not sure if we still use it. +1 for keeping it.

**Comment by guillim** [comment]
I can answer to 
`context_window_size: 2000` present in pipelines.yaml but not in the evaluation script. Since it's used for presenting to the user a some text around the answer for context, I imagine we need it for deployment and therefore should keep it.

=> yes we need to keep this. it's simply the number of characters you want to get around the answers. I need to specify this when I have longer answers that need to be displayed fully (the default case crops to only 200 characters from the top of my head)

**Comment by guillaumecherel** [comment]
>       * The ElasticsearchDocumentStore used is the same for all retriever types in the evaluation script (`retriever_reader_eval_squad.py`) except for "dpr", where it is given the argument `similarity = "dot_product"` instead of `"cosine"`. Is this correct or should we always use "cosine"?

Use dot_product for dpr and cosine for the others.

>       * The parameter `embedding_dim` for the ElasticsearchDocumentStore is 768 in the evaluation script but 512 in `pipelines.yaml`.

Use 512 (with distiluse).

>       * The `search_fields` value is `["name", "text"]` in the evaluation script but `"text"` only in `pipelines.yaml`.

Use `["name", "text"]`

>       * The `document_index` field is `"document_xp"` in the evaluation script but  `"document_elasticsearch"` in `pipelines.yaml`. Do we need to keep the different names in a deployment or evaluation settings? I imagine that could be needed if we sometimes run both settings with the same elasticsearch instance. If we don't we could use only one name.

Use "document_elasticsearch".

>       * `custom_mappings` are present in the evaluation script but not in `pipelines.yaml`

Put custom mappings in the yaml.
